---
title: "Chapter4_extraNotes"
author: "Munir Nur"
date: "4/26/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rethinking)
```


```{r}
pos <- replicate( 1000 , sum( runif(16,-1,1) ) )
plot(density(pos))
```

```{r}
prod( 1 + runif(12,0,0.1) )
growth <- replicate( 10000 , prod( 1 + runif(12,0,0.1) ) )
density( growth , norm.comp=TRUE )
hist(growth)
```

```{r}
big <- replicate( 10000 , prod( 1 + runif(12,0,0.5) ) )
small <- replicate( 10000 , prod( 1 + runif(12,0,0.01) ) )
hist(big) ; hist(small)
```

```{r}
curve( dnorm( x, 178, 20) , from=100, to=250)
curve( dunif( x , 0 , 50 ) , from=-10 , to=60 )

```

```{r}
library(rethinking)
data(Howell1)
d <- Howell1

```

```{r}
set.seed(2971)
N <- 100                   # 100 lines
a <- rnorm( N , 178 , 20 )
b <- rnorm( N , 0 , 10 )

plot( NULL , xlim=range(d2$weight) , ylim=c(-100,400) ,
    xlab="weight" , ylab="height" )
abline( h=0 , lty=2 )
abline( h=272 , lty=1 , lwd=0.5 )
mtext( "b ~ dnorm(0,10)" )
xbar <- mean(d2$weight)
for ( i in 1:N ) curve( a[i] + b[i]*(x - xbar) ,
    from=min(d2$weight) , to=max(d2$weight) , add=TRUE ,
    col=col.alpha("black",0.2) )
```